/**
 * Database types for GeoERP Mobile.
 *
 * Source of truth: types/database.generated.ts (auto-generated by Supabase CLI
 * from the geoerp web repo). Run `./scripts/sync-types.sh` to update after
 * any migration change.
 *
 * This file re-exports the generated Database type and provides convenience
 * aliases used throughout the mobile app.
 */

import type { Database, Json } from "./database.generated";

export type { Database, Json };

// ---------------------------------------------------------------------------
// Helper: Extract a table's Row type from the generated Database interface.
// ---------------------------------------------------------------------------
type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

// ---------------------------------------------------------------------------
// GeoJSON geometry types (PostGIS columns come as `unknown` in generated types)
// ---------------------------------------------------------------------------
export interface GeoPoint {
  type: "Point";
  coordinates: [number, number]; // [lng, lat]
}

export interface GeoLineString {
  type: "LineString";
  coordinates: [number, number][];
}

// ---------------------------------------------------------------------------
// Domain-specific string literal types.
// These narrow the generic `string` from the generated types to the known
// values used in the application. Keep in sync with DB constraints/check values.
// ---------------------------------------------------------------------------
export type UserRole = "admin" | "supervisor" | "operator" | "trinchero";

export type ServiceType =
  | "gas"
  | "power"
  | "water"
  | "telecom"
  | "sewer"
  | "other";

export type ServiceStatus = "to_open" | "found" | "not_found";

export type DamageSeverity = "low" | "medium" | "high" | "critical";

// ---------------------------------------------------------------------------
// Table row types (convenience aliases matching previous interface names)
// ---------------------------------------------------------------------------
export type Project = Tables<"projects">;

type LineSegmentRow = Tables<"line_segments">;

/** LineSegment with geometry cast to GeoLineString. */
export interface LineSegment extends Omit<LineSegmentRow, "geometry"> {
  geometry: GeoLineString;
}

export type ServiceRow = Tables<"services">;

/** Service with geometry cast to GeoPoint, narrowed enum fields, and optional joined line_segment. */
export interface Service extends Omit<ServiceRow, "geometry" | "status" | "service_type"> {
  geometry: GeoPoint;
  status: ServiceStatus;
  service_type: ServiceType;
  line_segment?: {
    id: string;
    name: string;
    project_id: string | null;
  } | null;
}

export type ServicePhotoRow = Tables<"service_photos">;

/** ServicePhoto with geometry cast to GeoPoint. */
export interface ServicePhoto extends Omit<ServicePhotoRow, "location"> {
  location: GeoPoint | null;
}

export type PreExistingDamageRow = Tables<"pre_existing_damages">;

/** PreExistingDamage with geometry cast to GeoPoint. */
export interface PreExistingDamage
  extends Omit<PreExistingDamageRow, "geometry"> {
  geometry: GeoPoint;
}
